### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mrwuh** [huazai1992/HGCN#1]
Can you give me the Code for data set processing? I don't quite understand how to get those four parts of the own dataset

**Comment by huazai1992** [comment]
> Can you give me the Code for data set processing? I don't quite understand how to get those four parts of the own dataset

Hi, I have updated the processing code. You can use it to process your own dataset (the node and edge files described in the code).

**Comment by mrwuh** [comment]
thanks

**Comment by mrwuh** [comment]
I'm very sorry to disturb you again. I have tried your code for processing data sets many times, but I still don't understand what the data set you input is. Can you give me a case of Cora or DBLP dataset? Thank you very much.

**Comment by huazai1992** [comment]
Hi, I have added a case, which contains one edge file and two node files. You can generate the files following the examples.

**Comment by mrwuh** [comment]
labels = read_dat(path='', file_name='')
What is the file read here？

**Comment by huazai1992** [comment]
The format of the label file is the same as the node file, i.e., <node_index>\t<label_index>.

**Comment by huazai1992** [comment]
Note that, if there exist some nodes that have no labels, the label index should be started from 1 and set the 'ispart' as True. And if all nodes have labels, the label index could be 0 and set the 'ispart' as False.

**Comment by mrwuh** [comment]
def gen_labels(target_type, ispart=False):
    # the label file: <node_idx>\t<label_idx>. if <node_idx> has not a label, <label_idx> is fixed as 0,
    labels = read_dat(path='data_example/', file_name='P.txt')
I made a mistake after I wrote this ：MemoryError: Unable to allocate array with shape (19396, 19396) and data type float64

**Comment by huazai1992** [comment]
Sorry, the gen_labels(target_type, ispart=False) is directly copied from other datasets' processing code, of which input format is the same as *.label.all. 
I have updated the new code, you can try it.

**Comment by mrwuh** [comment]
P. label.all Is the label of the target node after processing the data set

P. label.part Is the collation of the target node and its tags

Is that right?

**Comment by huazai1992** [comment]
Yes. And P.label.part only includes the nodes that have labels.

**Comment by mrwuh** [comment]
I see a  *.feat.npz in your dataset. What is the representation of a node?

**Comment by huazai1992** [comment]
It depends on your datasets. For example, we use a bag-of-words representation of all the paper titles as content feature for each paper node. You can generate your own content features and save it by sp.save_npz().

**Comment by mrwuh** [comment]
Can you give me the access to Cora and DBLP datasets，I'd like to check if I'm dealing with it correctly

**Comment by huazai1992** [comment]
Do you mean raw data?

**Comment by mrwuh** [comment]
yes

**Comment by huazai1992** [comment]
Such as the file PA.txt, P.txt, and A.txt?

**Comment by huazai1992** [comment]
Or the dataset that is never processed

**Comment by mrwuh** [comment]
dataset  never processed

**Comment by huazai1992** [comment]
Sorry, I can only find the DBLP dataset (I put it in the "data_example"). I think you can use it to check your code.

**Comment by mrwuh** [comment]
thanks

**Comment by mrwuh** [comment]
Excuse me again. Is the adjacency matrix of APC in DBLP dataset understood as an adjacency matrix composed of AC obtained by AP and PC?

**Comment by huazai1992** [comment]
Yes

**Comment by mrwuh** [comment]
Sorry to disturb you again, if I don't use * feat.npz File, I can't get truefeature. Is there any solution?

**Comment by huazai1992** [comment]
I think you can try to comment out the code "targetFeature = concatenate([org_feature, relFeature[target_index]], axis=1)" in model.py as well as other related codes. But I do not know whether it would affect the results.

**Comment by mrwuh** [comment]
Can you  send A.feat.npz of DBLP datasets to me? I'll try the result of the file first, and then I'll see the result without the file.

**Comment by huazai1992** [comment]
Can you send me an email? Then, I can reply to you with the data.

**Comment by mrwuh** [comment]
Can I upload files directly to GitHub？

**Comment by mrwuh** [comment]
Or you send me your email

**Comment by huazai1992** [comment]
OK, wait a moment. My network speed is slow

**Comment by huazai1992** [comment]
I have put it in "data"

**Comment by mrwuh** [comment]
my accuracy only 0.7103,is it my dataset processing error?

**Comment by huazai1992** [comment]
you can try "python train.py --dataset dblp --kernel-size 4 --inception-depth 3 --label-propagation 0 --epochs 16 --seed 8"

**Comment by mrwuh** [comment]
thanks,the result is same as yours

**Comment by huazai1992** [comment]
OK
